export enum ItemCategory {
  MOCHILA = 'MOCHILA',
  CARTEIRA = 'CARTEIRA',
  DOCUMENTO = 'DOCUMENTO',
  CHAVE = 'CHAVE',
  TELEFONE = 'TELEFONE',
  ELECTRONICOS = 'ELECTRONICOS',
  ROUPA = 'ROUPA',
  JOIA = 'JOIA',
  LIVRO = 'LIVRO',
  OUTRO = 'OUTRO'
}
